monolog:
    channels: ['kunlabo']
    handlers:
        buffered_file:
            type: buffer
            handler: file
            level: info
            channels: ["kunlabo"]
            formatter: 'monolog.formatter.json'

        file:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]