version: '3.8'

services:
    nginx:
        image: nginx:1.21.1-alpine
        ports:
            - 8080:80
        volumes:
            - ./kunlabo:/var/www/kunlabo
            - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/kunlabo
        depends_on:
            - mercure

    python:
        build:
            context: ./
            dockerfile: ./ops/python/Dockerfile
        command: python -u ./kunlabo/main.py
        volumes:
            - ./kunlabo/public/uploads/agents:/usr/src/kunlabo/agents
            - ./python/main.py:/usr/src/kunlabo/main.py
        environment:
            HUB_URL: http://mercure/.well-known/mercure
        working_dir: /usr/src
        depends_on:
            - mercure

    mercure:
        image: dunglas/mercure:v0.12.1
        ports:
            - 9090:80
        volumes:
            - ./volumes/mercure/data:/data
            - ./volumes/mercure/config:/config
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: ${JWT_SECRET_KEY}
            MERCURE_SUBSCRIBER_JWT_KEY: ${JWT_SECRET_KEY}
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins *
                anonymous
                subscriptions
        depends_on:
            - php

    php:
        build: ./ops/php-fpm
        volumes:
            - ./kunlabo:/var/www/kunlabo
        working_dir: /var/www/kunlabo
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_NAME: ${MYSQL_DATABASE}
            DB_VERSION: 8.0.26
            MERCURE_URL: http://mercure/.well-known/mercure
            MERCURE_PUBLIC_URL: http://localhost:9090/.well-known/mercure
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0.26
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - 3306:3306
        volumes:
            - ./volumes/db/data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ~
            MYSQL_USER: ~
            MYSQL_PASSWORD: ~
            MYSQL_ROOT_PASSWORD: ~