version: '3.8'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
        ports:
            - 9200:9200
        volumes:
            - ./volumes/elasticsearch:/usr/share/elasticsearch/data
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ulimits:
            memlock:
                soft: -1
                hard: -1

    logstash:
        image: docker.elastic.co/logstash/logstash:7.14.0
        volumes:
            - ./ops/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
        depends_on:
            - elasticsearch

    filebeat:
        build: ./ops/filebeat
        volumes:
            - ./kunlabo/var/log:/var/log/kunlabo
            - ./volumes/filebeat:/usr/share/filebeat/data
        depends_on:
            - logstash

    kibana:
        image: docker.elastic.co/kibana/kibana:7.14.0
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
