version: '3.8'

services:
  nginx:
    image: nginx:1.21.1-alpine
    ports:
      - 8080:80
    volumes:
      - ./kunlabo:/var/www/kunlabo
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./ops/php-fpm
    volumes:
      - ./kunlabo:/var/www/kunlabo