user_controllers:
    resource: '../src/User/Infrastructure/Framework/Controller'
    type: annotation

shared_controllers:
    resource: '../src/Shared/Infrastructure/Framework/Controller'
    type: annotation

engine_controllers:
    resource: '../src/Engine/Infrastructure/Framework/Controller'
    type: annotation