user_controllers:
    resource: '../src/User/Infrastructure/Framework/Controller'
    type: annotation

home_controllers:
    resource: '../src/Home/Infrastructure/Framework/Controller'
    type: annotation