user_controllers:
    resource: '../src/User/Infrastructure/Framework/Controller'
    type: annotation

shared_controllers:
    resource: '../src/Shared/Infrastructure/Framework/Controller'
    type: annotation

engine_controllers:
    resource: '../src/Engine/Infrastructure/Framework/Controller'
    type: annotation
    prefix: engines

agent_controllers:
    resource: '../src/Agent/Infrastructure/Framework/Controller'
    type: annotation
    prefix: agents

study_controllers:
    resource: '../src/Study/Infrastructure/Framework/Controller'
    type: annotation
    prefix: studies