user_controllers:
    resource: '../src/User/Infrastructure/Framework/Controller'
    type: annotation

home_controllers:
    resource: '../src/Shared/Infrastructure/Framework/Controller'
    type: annotation