# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Kunlabo\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    _instanceof:
        # all services implementing the CommandHandler interface
        # will be registered on the command.bus bus
        Kunlabo\Shared\Application\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        # all services implementing the QueryHandler interface
        # registered on the query.bus bus
        Kunlabo\Shared\Application\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

        # all services implementing the DomainEventSubscriber interface
        # registered on the domain.bus bus
        Kunlabo\Shared\Application\Bus\Event\DomainEventSubscriber:
            tags:
                - { name: messenger.message_handler, bus: event.bus }