parameters:
    DB_USER: '%env(DB_USER)%'
    DB_PASSWORD: '%env(DB_PASSWORD)%'
doctrine:
    dbal:
        url: '%env(resolve:DB_URL)%'
        types:
            aggregate_uuid: Kunlabo\Shared\Infrastructure\Persistence\Doctrine\Types\AggregateUuidType
            role_array: Kunlabo\User\Infrastructure\Persistence\Doctrine\Types\RoleArrayType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            KunlaboUser:
                type: xml
                dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'Kunlabo\User\Domain'
                alias: User
            KunlaboShared:
                type: xml
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'Kunlabo\Shared\Domain'
                alias: Shared
